name: Build-and-Test

on: [push]

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Release
      run: |
        cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: udl-mac-intel
        path: ./target/release/udl

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Release
      run: |
        cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: udl-linux-intel
        path: ./target/release/udl
